image: node:latest

cache:
  paths:
    - src/node_modules/

linter:
  script:
    - cd ./src
    - npm install
    - npm run lint

tests:
  script:
    - cd ./src
    - npm install
    - npm run test

coverage:
  script:
    - cd ./src
    - npm install
    - npm run coverage
  artifacts:
    paths:
      - src/coverage
    expire_in: 30 days

build:
  script:
    - cd ./src
    - npm install
    - npm run build
  artifacts:
    paths:
      - src/dist
    expire_in: 30 days
