version: "3.9"
services:
  backend1:
    build: ./src
    volumes:
      - ./config/backend/default.json:/usr/src/app/config/default.json
    links:
      - "postgres:postgres"
      - "mongo:mongo"
    depends_on:
      - mongo
      - postgres
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  postgres:
    restart: always
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata2
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    cpu_count: 4
    mem_limit: 6g
  nginx:
    image: 'byjg/nginx-extras'
    ports:
      - "9090:9090"
    links:
      - "backend1:backend1"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/static
    depends_on:
      - backend1